//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDMT_DOAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGGHIDAUGIA
    {
        public int MA { get; set; }
        public string NHACUNGCAP { get; set; }
        public string SANPHAM { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public Nullable<int> GIA { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP1 { get; set; }
        public virtual SANPHAM SANPHAM1 { get; set; }
    }
}
