//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDMT_DOAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THANHVIEN()
        {
            this.DONHANGs = new HashSet<DONHANG>();
            this.THANHTOANONLINEs = new HashSet<THANHTOANONLINE>();
        }
    
        public int MA { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string TEN { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string THONGTINMOTA { get; set; }
        public string CUSTOMER_KEY { get; set; }
        public Nullable<int> LoaiThanhVien { get; set; }
        public Nullable<bool> DADANGNHAP { get; set; }
        public string MAKICHHOAT { get; set; }
        public Nullable<bool> DAXOA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        public virtual LOAITHANHVIEN LOAITHANHVIEN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANHTOANONLINE> THANHTOANONLINEs { get; set; }
    }
}
